# By default, SwiftLint uses a set of sensible default rules you can adjust:

opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - anyobject_protocol
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  # - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - explicit_self
  - fatal_error_message
  - first_where
  - force_unwrapping
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_random
#  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - multiline_arguments
  - multiline_parameters
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - strong_iboutlet
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - xct_specific_matcher

disabled_rules: # rule identifiers turned on by default to exclude from running
  - closure_parameter_position
  - identifier_name
  - nesting
  - todo
  - type_name
  - unused_closure_parameter
  - inclusive_language # правило толерантности языка, ругается на slave, master e.t.c
  - comment_spacing
  - redundant_type_annotation
  - redundant_optional_initialization
  - void_function_in_ternary
# Custom rules --------------------------------

custom_rules:
#  newline_after_capture_list:
#    included: ".*\\.swift"
#    name: "Newline after capture list"
#    regex: '(?-s)(\{\n?.* in\n[^\n]+\w)'
#    severity: warning
#  capture_list_on_newline:
#    included: ".*\\.swift"
#    name: "Capture list on newline"
#    regex: '(?-s)(\{.*in\n)'
#    severity: warning
  unnecessary_leading_void_in:
    name: "Unnecessary -> Void in at the end of the line"
    regex: '(-> (Void|\(\)) in$)'
    message: "Unnecessary '-> Void in' at the end of the line. Use only 'in'"
    severity: warning
  deprecated_uiwebview:
    included: ".*\\.[swift|m]"
    excluded: ".*Tests\\.[swift|m]"
    name: "Deprecated UIWebView Usage"
    regex: "UIWebView"
    match_kinds:
      - typeidentifier
    message: "ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information."
    severity: warning

# Directories ---------------------------------

excluded:
  - .bundle
  - fastlane
  - Carthage
  - DerivedData
  - Pods
  - Generated
  - Resources
  - Vendor/AnyCodable
  - Vendor/WhatsAppStickerPack
  - Vendor/AnimationRestoration
  - Vendor/Logging/Sources/Logging/swift-log
  - Templates
  - MyTemplates

# Don't touch this
reporter: "xcode"

# Configuration -------------------------------

file_length:
  warning: 2048
  error: 100000

function_body_length:
  warning: 256
  error: 100000

# Ignore warnings for UIKit type `NSDiffableDataSourceSnapshot<SectionIdentifierType, ItemIdentifierType>`
generic_type_name:
  max_length: 30

type_body_length:
  warning: 768
  error: 100000

line_length:
  warning: 512
  error: 100000

identifier_name:
  min_length:
    warning: 1
    error: 1
  max_lenght:
    warning: 64
    error: 100000
  allowed_symbols: "_"

number_separator:
  minimum_length: 5
  minimum_fraction_length: 5

large_tuple:
  warning: 6
  error: 100000

function_parameter_count:
  warning: 17
  error: 100000

cyclomatic_complexity:
  warning: 65
  error: 100

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

# Uncomment and configure this in project's branch
deployment_target:
  iOS_deployment_target: "15.0"
 # macOS_deployment_target: "10.14"
 # watchOS_deployment_target: "5.0"
 # tvOS_deployment_target: "12.0"
